Added Collision?
self.rockSprite created - list which contains rocks created by pressing space.  Should only be one in existence at a time.
-pressing space now creates a rock, then feeds its data to the cannon
-added collision loop, which now isn't operating because of the following error:
'File "C:\Users\John\Appdata\Romaing\Python\Python36\site-packages\pygame\sprite.py", line 1300, in collide_rect
return left.rect.colliderect(right.rect)
AttributeError: 'Group' object has no attribute 'rect' "
-collision placed inside a try statment
-blit placed inside finally statement